import { Header, Sidebar } from "@/components";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Tiktok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <Header />

        {/* Sidebar */}
        <div className="hidden md:inline">
          <Sidebar />
        </div>
      </main>
    </>
  );
}
